### ISSUE TITLE
iOS Mail body blank

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/connector-send-email#103]
When using the built in Apple iOS mail client, all emails have a blank body. Works in the Gmail App and on the desktop (Using MacOS mail).

![image](https://user-images.githubusercontent.com/535300/83575381-352f1c00-a4e4-11ea-96f5-e6f841f2b4a8.png)

**Comment by velkymx** [comment]
You can test with the staging server using this process: https://staging-pm4.processmaker.net/modeler/183

**Comment by PMQABen** [comment]
Works fine on local VM, waiting on release-testing to be updated to confirm.
