### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by sanjacornelius** [ProcessMaker/connector-send-email#44]
- [x] Task Inspector Extension: Notification Toggle, When to Send, to, subject, body, etc: @sanjacornelius 
- Save settings to pm:config attribute on bpmn task. Example: https://github.com/ProcessMaker/package-webentry/blob/947808b6a91d42d3077f3d135e3819dc0bdb8d21/resources/assets/js/components/WebEntry.vue#L168
- [ ] Email Events Listener in package provider - @marcoAntonioNina 
- [ ] Create subprocess as part of the package install. [Example](https://github.com/ProcessMaker/package-actions-by-email/blob/d144189f73f0d5ab74f360a92106e63a790a511a/src/Seeds/Seeder.php#L108)
- [ ] Listener should check pm:config if email notification is for start or end and start the new sub-process accordingly
- [ ] Listener can find the sub-process by its key field and start it with `\ProcessMaker\Facades\ WorkflowManager::triggerStartEvent($process, $event, $data);`
  - $data should be the pm:config array MERGED with current $data
- [ ] Exclusive gateways in subprocess:
  - First gateway expression - if expression exists:
    - flow `email_notification_config.expression != ""` go to second gateway
    - flow `email_notification_config.expression == ""` go to send email
  - Second gateway: evaluate expression using mustache syntax
    - `{{ email_notification_config.expression }}` go to send email
    - `!{{ email_notification_config.expression }}` (starts with `!` to negate it) go to end event
- [ ] Email connector in sub process
  - to `{{ email_notification_config.email }}`
  - name `{{ email_notification_config.targetName }}`
  - body `{{ email_notification_config.textBody }}`
  - screen `{{ email_notification_config.screenRef }}` ***Email connector should use the screen and igore textBody if screenRef is present... I think***
  - Body and ScreenRef mustache values need to be added *manually* to the bpmn since the UI doesn't allow it. Make sure its encoded correctly.
- [ ] Add Test: [See this example](https://github.com/ProcessMaker/package-actions-by-email/blob/master/test/Feature/ActionsByEmailTest.php). It's using call-activity and we are not (the listener is starting the process instead) but the test has some good ideas
  - Check email sent at start or end of task
  - If expression exists, email only sent if expression evaluates true

**Comment by nolanpro** [comment]
@marcoAntonioNina the listener updates look good, could you add a feature test for it? Here is an example of how I get emails from the webentry test: https://github.com/ProcessMaker/connector-actions-by-email/blob/dd9da9fc368d951bfb21502ea3c471380f56a7eb/test/Feature/ActionsByEmailTest.php#L158

I think the test should have bpmn where [you can str_replace ids](https://github.com/ProcessMaker/connector-actions-by-email/blob/dd9da9fc368d951bfb21502ea3c471380f56a7eb/test/Feature/ActionsByEmailTest.php#L70) to test the screen

We haven't finished adding the pm:conifg yet but I think it's going to be in the format in the description above. You can add it manually to the bpmn file for the tests. Make sure it has "activated" or "completed" in the config and test that it gets sent at the right time. Thanks

**Comment by velkymx** [comment]
This should use a processes for processing the notification.

**Comment by nolanpro** [comment]
@marcoAntonioNina I merged your test into EmailNotificationsTest.php. Let's use that test for now.

Looks like the gateway expression field is not parsing mustache. Can you look into this?

in sub-process.bpmn
```
<bpmn:conditionExpression xsi:type="bpmn:tFormalExpression">{{ email_notifications.expression }}</bpmn:conditionExpression>
```
results in
```
Syntax error. A hash key must be a quoted string, a number, a name, or an expression enclosed in parentheses (unexpected token "punctuation" of value "{" around position 2 for expression `{{ email_notifications.expression }}
```
from the test when triggering the start event (`phpunit vendor/processmaker/connector-send-email/tests/feature/EmailNotificationsTest.php` on line 36)

Also, I was getting some weird endless loop going back and forth between node_6 and node_7 but that might be the same problem.

**Comment by nolanpro** [comment]
@marcoAntonioNina I've updated the test to use a mock script runner and it works now. You might need to uninstall and reinstall the package to get working since it does some strange stuff with psr-4 autoload.

When you run the test you'll see a failure. It can't find `Here is a plain text body with some_data: abc`. This is because the body has 2 levels of mustasche syntax, so the rendered output has `Here is a plain text body with some_data: {{ some_data }}`. Would could run `$mustache->render(...)` twice in EmailController line 64 but do you think there is a better way? Should we change the sub process.bpmn? I'm not sure, i'll leave it up to you.

Also, when that's fixed, feel free to add more assertions to EmailNotificationsTest.php. Thanks!
