### ISSUE TITLE
Selected users & groups are not displaying

### ISSUE THREAD

**Issue by sanjacornelius** [ProcessMaker/connector-send-email#46]
**Reproduce:**
1. Create a new 'send email' node
2. Select some users or groups
3. Save the bpmn
4. Navigate back to the 'send email' node

**Expected:**
 Previously selected users/groups for that node are displayed.

**Result:**
The previously selected users & groups are not displayed.

**Comment by nolanpro** [comment]
This appears to be fixed. Please re-open if not
