### ISSUE TITLE
URLs Getting Rewritten

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/connector-send-email#82]
Adding a link to a request in a rich text editor in a email screen is not working as expected, if you set the same domain of your server the system will change it to ../../../../ when you save the link.

This causes that when a request run and you get the email with the link you will get an "invalid url" message.

See video: https://www.dropbox.com/s/mo0098pbbeqs60x/issue%20with%20links.mp4?dl=0

This is 4.0.2 and the same behavior was replicated in 2 different servers.

This has been reported by ProcessMaker France

Note: This affects all screens that use the Rich Text control.

**Comment by nolanpro** [comment]
Fixing in https://github.com/ProcessMaker/vue-form-elements/issues/173
